name: release

on:
  workflow_dispatch:
    inputs:
      VIPS_VERSION:
        description: 'LibVips Version'  

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Restore dependencies
      run: dotnet restore
    - name: Package
      run: dotnet run --project packager/packager.csproj
      env:
        VIPS_VERSION: ${{ github.event.inputs.VIPS_VERSION }}
    - name: Push
      run: |
        dotnet nuget add source --username ${{ secrets.NUGET_USERNAME }} --password ${{ secrets.NUGET_PASSWORD }} --store-password-in-clear-text --name "nuget_target" "${{ secrets.NUGET_REGISTRY_URL }}"
        dotnet nuget push "artifacts/*.nupkg" --api-key ${{ secrets.NUGET_APIKEY }} --source "nuget_target" --skip-duplicate
